services:
  setup:
    image: smallstep/step-ca:latest
    container_name: step-ca-setup
    user: root
    entrypoint: /bin/sh
    environment:
      - CA_PASSWORD=${CA_PASSWORD}
    command: -c "mkdir -p /home/step/secrets /opt/logs/step-ca /opt/logs/watchtower && echo -n \"${CA_PASSWORD}\" > /home/step/secrets/password && chown -R ${PUID}:${PGID} /home/step && chown -R ${PUID}:${PGID} /opt/logs"
    volumes:
      - ./step_data:/home/step
      - ./logs:/opt/logs

  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      setup:
        condition: service_completed_successfully
    ports:
      - "9000:9000"
    environment:
      DOCKER_STEPCA_INIT_NAME: "Internal Root CA"
      DOCKER_STEPCA_INIT_DNS_NAMES: "localhost,${DOMAIN_CA}"
      DOCKER_STEPCA_INIT_ACME: "true"
      DOCKER_STEPCA_INIT_PASSWORD: ${CA_PASSWORD}
      STEP_CA_PASSWORD_FILE: /home/step/secrets/password
    volumes:
      - ./step_data:/home/step
      - ./logs/step-ca:/var/log/step-ca
    entrypoint: /bin/bash -c "ls -la /home/step/secrets; /bin/bash /entrypoint.sh step-ca --password-file=/home/step/secrets/password 2>&1 | tee -a /var/log/step-ca/system.log"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "15m"
    healthcheck:
      test: [ "CMD", "step", "ca", "health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  watchtower:
    image: nickfedor/watchtower:latest
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/watchtower:/var/log/watchtower
    command: --interval 86400 --cleanup --label-enable
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "15m"
